apiVersion: v1
kind: Service
metadata:
  name: vuln-spring
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: vuln-spring
