apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - image: vulhub/spring-cloud-function:3.2.2
          name: spring
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always