apiVersion: apps/v1
kind: Deployment
metadata:
  name: atomic-red
  labels:
    app: atomic-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atomic-red
  template:
    metadata:
      labels:
        app: atomic-red
    spec:
      containers:
        - name: atomic-red
          image: 10.0.0.180:5000/atomicredteam
          imagePullPolicy: "IfNotPresent"
          command: ["sleep", "3560d"]
          securityContext:
            privileged: true
      nodeSelector:
        kubernetes.io/os: linux