apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  server: localhost
  path: /home/ubuntu/mongoStorage
  readOnly: "false"
reclaimPolicy: Retain
