apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: redis
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: redis
  template: 
    metadata: 
      labels: 
        app: redis
    spec:
      containers: 
      - name: redis
        image: 10.0.0.180:5000/localredis:latest
        ports: 
        - containerPort: 6379
