apiVersion: v1
kind: Service
metadata:
  name: vuln-redis
spec:
  type: NodePort
  ports:
    - name: "redis"
      port: 6379
      targetPort: 6379
      nodePort: 30079
  selector:
    app: vuln-redis