apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuln-redis
  template:
    metadata:
      labels:
        app: vuln-redis
    spec:
      containers:
        - image: 10.0.0.180:5000/vuln-redis
          name: vuln-redis
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always