apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cpu
spec:
  replicas: 0
  selector:
    matchLabels:
      app: cpu
  template:
    metadata:
      labels:
        app: cpu
    spec:
      containers:
      - name: cpu
        image: docker.io/maant001/cpu-intensive:latest
        securityContext:
          capabilities:
            drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
        stdin: true
        tty: true
