# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.4
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-10-31T19:54:59Z"
  labels:
    app: lovinglamarr
  name: lovinglamarr
spec:
  containers:
  - image: docker.io/maant001/diskrw-intensive:latest
    name: lovinglamarr
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE

