apiVersion: apps/v1
kind: Deployment
metadata:
  name: atomicred
  namespace: atomic-red
  labels:
    app: atomic-red
spec:
  replicas: 2
  selector:
    matchLabels:
      app: atomic-red
  template:
    metadata:
      labels:
        app: atomic-red
    spec:
      containers:
        - name: atomic-red
          image: localhost:5000/redcanary/invoke-atomicredteam
          imagePullPolicy: "IfNotPresent"
          command: ["sleep", "3560d"]
          securityContext:
            privileged: true
      nodeSelector:
        kubernetes.io/os: linux