apiVersion: v1
kind: Pod
metadata:
  name: atomic-red-restore
  labels:
    app: atomic-red-restore
spec:
  containers:
    - name: atomic-red
      image: 10.0.0.180:5000/atomicredteam:checkpoint
      imagePullPolicy: Always
      command: [ "sleep", "3560d" ]
      securityContext:
        privileged: true
  nodeSelector:
    kubernetes.io/os: linux
