apiVersion: v1
kind: Pod
metadata:
  name: redis-restore
  annotations:
    io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel: "true"
  labels:
    app: redis-restore
spec:
  containers:
  - name: redis-restore
    image: 10.0.0.180:5000/redis:checkpoint
    resources: 
      limits: 
        memory: "2Gi"
    imagePullPolicy: Always
    securityContext: 
      allowPrivilegeEscalation: true
      seLinuxOptions: 
        level: s0:c0
  imagePullSecrets:
  - name: registry-credentials
  restartPolicy: Never
