apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flask
spec:
  serviceName: flask-service
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-hello-tony
        image: docker.io/maant001/flask-app-tony:latest
        stdin: true
        tty: true
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask
  ports:
      - port: 80
        protocol: TCP
        targetPort: 5000
