apiVersion: v1
kind: Pod
metadata:
  name: cpu
  labels:
    app: cpu
spec:
  containers:
  - name: cpu
    image: 10.0.0.180:5000/localcpusinglecore:latest
    command: ["/bin/sh", "-c"]
    args: ["python3 /cpu_intensive/cpu_singlecore.py"]
