apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cpu
spec:
  serviceName: cpu-service
  replicas: 0
  selector:
    matchLabels:
      app: cpu
  template:
    metadata:
      labels:
        app: cpu
    spec:
      containers:
      - name: cpu-container
        image: 10.0.0.180:5000/localcpusinglecore:latest
        env:
        - name: NUM_CORES
          value: "3"
        - name: CPU_USAGE_PER_CORE
          value: "50"
        ## NEW APPROACH (comment lines out if doesnt work)
        command: ["/bin/sh", "-c"]
        args: ["python3 /cpu_intensive/cpu_state_machine_multicore.py '$(CPU_USAGE_PER_CORE)' '$(NUM_CORES)'"]
        ##
        volumeMounts:
        - name: cpulimit-volume
          mountPath: /usr/bin/cpulimit
      volumes:
      - name: cpulimit-volume
        hostPath:
          path: /usr/bin/cpulimit
          type: File
