apiVersion: v1
kind: Pod
metadata:
  name: cpu-again
  labels:
    app: cpu-again
  annotations:
    io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel: 'true'
spec:
  containers:
  - name: cpu-again
    image: 10.0.0.180:5000/localcpusinglecorerestore:checkpoint
    resources:
      limits:
        memory: "2Gi"
        cpu: "2"
      requests:
        memory: "1Gi"
        cpu: "1"
    imagePullPolicy: Always
    securityContext: 
      allowPrivilegeEscalation: true
      seLinuxOptions:
        level: s0:c0
